Add no-jira-ticket rule
Skyscanner/eslint-plugin-rules pull request #13
Opened 2024-05-29 17:02 UTC by youngji0827

Was looking to replicate a similar rule to Banana in Falcon to have a JIRA ticket linked to every TODO comment

Banana: https://github.skyscannertools.net/dingo/banana/blob/main/packages/eslint-plugin-custom-linting/lib/rules/jira-ticket-todo-comment.js
Falcon PR: https://github.skyscannertools.net/martech/falcon/pull/5607

@dominicfraser suggested that this may be a good addition to make available to all of the Skyscanner teams, so looking to add here in order to do so
https://github.skyscannertools.net/martech/falcon/pull/5607#discussion_r941687

### Changes
- Creates a rule to ensure all TODO comments have a linked JIRA ticket
- Merges format of Banana and proposed Falcon
- Allows for prefixes of `TODO`/`FIXME`/`@TODO`/`@FIXME`
- Allows for JIRA ticket references to be URL or just ticket reference
- Allows for optional description text

2024-05-30 08:35 UTC, dominicfraser commented on src/rules/no-jira-todo/README.md
> +```
I think we'll also need to export it here:
https://github.com/Skyscanner/eslint-plugin-rules/blob/96ee8f2944ab3877697f368162b4ff05156a8a22/index.js

2024-05-30 08:37 UTC, dominicfraser commented on src/rules/no-jira-todo/no-jira-todo.js
> +  'todo-error': 'All TODO comments must have a JIRA ticket',
We could expand this a bit to give a preferred example? 

We use 

```
JIRA ticket numbers must be added to all TODO/FIXME comments (e.g. TODO: DINGO-123)
```

Which:
1. Encourages people to align on one style, while not banning people from using others
2. If someone is new to the codebase they might not be familiar with the format, so this saves them a click looking for how other people do it and pass the regex

2024-05-30 15:15 UTC, Sybsw requested changes

2024-05-30 15:15 UTC, Sybsw commented on src/rules/no-jira-todo/no-jira-todo.js
> +Builds on eslint-plugin-react/forbid-component-props and extends to allow and Allow List to be provided as a regex.
```suggestion
Builds on eslint-plugin-react/forbid-component-props and extends to allow an Allow List to be provided as a regex.
```

2024-05-30 15:20 UTC, youngji0827 commented on src/rules/no-jira-todo/no-jira-todo.js
> +Builds on eslint-plugin-react/forbid-component-props and extends to allow and Allow List to be provided as a regex.
ah i had copy pasted this from the `forbid-component-props` files but doesn't quite relate here so have updated to the generic Skyscanner license used in the `no-axios` one too

2024-05-31 09:47 UTC, dominicfraser approved these changes
🎟️

2024-06-03 08:29 UTC, Sybsw approved these changes

2024-06-03 09:56 UTC, arnaugm approved these changes

2024-06-03 09:57 UTC, merged